// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tomlparseImpl
Rcpp::List tomlparseImpl(const std::string filename, bool verbose);
RcppExport SEXP RcppTOML_tomlparseImpl(SEXP filenameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(tomlparseImpl(filename, verbose));
    return __result;
END_RCPP
}
