# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tomlparse <- function(filename) {
    .Call('RcppToml_tomlparse', PACKAGE = 'RcppToml', filename)
}

